"""Statistics-day

Revision ID: 8758e9906c47
Revises: f5fbf1645456
Create Date: 2024-05-22 17:21:50.111161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8758e9906c47'
down_revision: Union[str, None] = 'f5fbf1645456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('countMetalRoll', sa.Integer(), nullable=False),
    sa.Column('sumWeightMetalRoll', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics_day')
    # ### end Alembic commands ###
